apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  labels:
    project: backstage-demo
    environment: dev
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: git@github.com:Heinux-Training/backstage-demo.git
    targetRevision: master
    path: application-files/aws-load-balancer-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "1"