apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default 
  sources:
  - repoURL: https://backstage.github.io/charts
    chart: backstage
    targetRevision: 2.6.2
    path: application-values/backstage
    helm:
      valueFiles:
      - $values/application-values/backstage/values.yaml
  - repoURL: git@github.com:Heinux-Training/backstage-demo.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m